name: push-resume

on: push
  push:
    branches:
      - main
    paths:
      - 'resume.pdf'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes file
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'resume.pdf'
        destination_repo: 'Yukezter/personal-website'
        destination_folder: 'public/assets'
        user_email: 'ray.b.hinchliffe@email.com'
        user_name: 'Yukezter'
